---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Bergi.
--- DateTime: 18.03.2022 3:25
---
function SpellCharge(hero,enemy)
    local dist=DistanceBetweenUnits(hero,enemy)
    local angle=AngleBetweenUnits(hero,enemy)
    local speed=30
    --print(hero,enemy,dist,angle,speed)
    BlzSetUnitFacingEx(hero,angle)
    UnitAddForceSimple(hero,angle,speed,dist,"ignoreAll")
end